<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704165202 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recording (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, audio_key VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, narrator VARCHAR(255) NOT NULL, story_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB532B53AA5D4036 ON recording (story_id)');
        $this->addSql('CREATE TABLE story (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, ean VARCHAR(13) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE recording ADD CONSTRAINT FK_BB532B53AA5D4036 FOREIGN KEY (story_id) REFERENCES story (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recording DROP CONSTRAINT FK_BB532B53AA5D4036');
        $this->addSql('DROP TABLE recording');
        $this->addSql('DROP TABLE story');
    }
}
